footer:
 jp: 日報アプリ
 eng: © 2020 フォーユー株式会社
todays_word: 
   - ベストを尽くして失敗したら、ベストを尽くしたってことさ
   - いつか、必ず、チャンスの順番が来ると信じなさい
   - 前向きにもがき苦しむ経験は、すぐに結果に結びつかなくても、必ず自分の生きる力になっていく,
   - 「負けたことがある」というのが　いつか　大きな財産になる
   - 「ゴールは遠いなぁ」と、がっかりするのも道のりです, 
   -  反省することは反省する。でも一度寝たら忘れる
   - 自分を少し抑えて、肩の力を抜けば、仕事は長続きする
   - 常に今日は明日の準備ですからね。今日やったことは必ず明日に返ってくるんです
   - 小さいことを積み重ねるのが、とんでもないところへ行くただひとつの道だと思っています
   - 一歩踏み出せるなら、もう一歩も踏み出せる
   - 自分がわかっていないことがわかるということが一番賢いんです
   - 成功の反対は失敗ではなく「やらないこと」だ
   - 家をきれいにする、約束を守る、お礼の手紙を書く、そういう基本をきっちり続けることが、自分の型の基本をつくってくれたと思っています
   - あきらめたらそこで試合終了だよ
   - 夢中で日を過ごしておれば、いつかはわかる時が来る。
catchcopy:
   - 他人には教えたくない日報
   - 日報にもドラマがあります
   - 運気をあげる日報
   - スマホ対応の日報
   - 毎日洗いざらい
title:
  - EX日報
  - サクッと日報
  - すぐレポ
  - 楽レポ
  - エクス日報
logo:
   - logo0.png
   - logo1.png
   - logo2.png
   - logo3.png
 